[package]
name = "aoc_2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
nalgebra = "0.32.3"
network-flow = "0.1.0"
num = "0.4.1"
z3 = "0.12.1"
